"""Regenerate common/scripted_effects/skonester_cw_tradition_picker_lists_generated.txt.

The tradition picker GUI shows global lists of culture traditions. CK3 has no way to
iterate the tradition database from script, so the keys are written out here: one list
for vanilla and one for A Game of Thrones (AGOT). At runtime the AGOT list is used when
skonester_compat_agot_loaded_trigger is true, otherwise the vanilla list.

Run after a CK3 or AGOT update:
    python tools/gen_cw_tradition_picker_lists.py --game-dir <CK3>/game --agot-dir <workshop>/2962333032
or set CK3_GAME_DIR and CK3_AGOT_DIR instead of passing the flags.
"""
import argparse
import glob
import os
import re
import sys

MOD_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(MOD_DIR, "common", "scripted_effects", "skonester_cw_tradition_picker_lists_generated.txt")
SUB = os.path.join("common", "culture", "traditions")

CATEGORIES = ["realm", "combat", "societal", "ritual", "regional"]
# Hidden traditions (is_shown = { always = no }) are listed on purpose: this is a cheat menu.
# Never listed: the mod's own player-only tradition, the decision-only oath tradition that the
# original list never had, and AGOT's debug tradition.
EXCLUDE = {"zhuge_chuantong", "oath_mend_the_fracture_tradition", "tradition_agot_debug"}


def top_level_objects(path):
    """Yield (key, body) for each top-level `key = { ... }` block in a script file."""
    text = open(path, encoding="utf-8-sig", errors="replace").read()
    text = re.sub(r"#[^\n]*", "", text)
    start = re.compile(r"(?m)^([A-Za-z_]\w*)\s*=\s*\{")
    pos = 0
    while True:
        m = start.search(text, pos)
        if not m:
            return
        depth, i = 0, m.end() - 1
        while i < len(text):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        yield m.group(1), text[m.end():i]
        pos = i + 1


def direct_child(body, key):
    """Return the text of `key = ...` at depth 0 of body (value or block contents), else None."""
    depth = 0
    for tok in re.finditer(r"\{|\}|\b%s\s*=\s*(\{|\w+)" % re.escape(key), body):
        t = tok.group(0)
        if t == "{":
            depth += 1
        elif t == "}":
            depth -= 1
        elif depth == 0:
            if tok.group(1) != "{":
                return tok.group(1)
            d, j = 1, tok.end()
            while j < len(body) and d:
                d += {"{": 1, "}": -1}.get(body[j], 0)
                j += 1
            return body[tok.end():j - 1]
    return None


def traditions(files):
    """Map tradition key -> category; later files override earlier ones."""
    found = {}
    for f in files:
        for key, body in top_level_objects(f):
            found[key] = body
    out = {}
    for key, body in found.items():
        if key in EXCLUDE:
            continue
        cat = direct_child(body, "category")
        if cat in CATEGORIES:
            out[key] = cat
    return out


def effective_files(*dirs):
    """Files as the game loads them: a later dir's file replaces an earlier one with the same name."""
    by_name = {}
    for d in dirs:
        for f in glob.glob(os.path.join(d, SUB, "*.txt")):
            by_name[os.path.basename(f)] = f
    return [by_name[n] for n in sorted(by_name)]


def emit_effect(name, trads):
    lines = [f"{name} = {{"]
    for cat in CATEGORIES:
        keys = sorted(k for k, c in trads.items() if c == cat)
        lines.append(f"  # {cat} ({len(keys)})")
        for k in keys:
            lines.append(f"  add_to_global_variable_list = {{ name = skonester_cw_{cat}_tradition_list target = culture_tradition:{k} }}")
        lines.append("")
    lines.append("}")
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--game-dir", default=os.environ.get("CK3_GAME_DIR"), help="CK3 game/ directory (or CK3_GAME_DIR)")
    ap.add_argument("--agot-dir", default=os.environ.get("CK3_AGOT_DIR"), help="AGOT workshop directory (or CK3_AGOT_DIR)")
    args = ap.parse_args()
    for flag, val in (("--game-dir", args.game_dir), ("--agot-dir", args.agot_dir)):
        if not val or not os.path.isdir(os.path.join(val, SUB)):
            sys.exit(f"{flag}: no {SUB} under {val!r}")

    vanilla = traditions(effective_files(args.game_dir, MOD_DIR))
    agot = traditions(effective_files(args.game_dir, args.agot_dir, MOD_DIR))

    out = [
        "# AUTO-GENERATED by tools/gen_cw_tradition_picker_lists.py from CK3, A Game of Thrones and Skonester",
        "# culture tradition definitions. Rebuild this file when a game or AGOT update adds or removes traditions.",
        "# AGOT-only keys do not exist in vanilla, so vanilla logs one harmless \"Failed to find\" error per key at",
        "# load; the AGOT branch never runs there.",
        "",
        "skonester_cw_build_tradition_picker_lists_effect = {",
        "  skonester_cw_clear_tradition_picker_lists_effect = yes",
        "  if = {",
        "    limit = { skonester_compat_agot_loaded_trigger = yes }",
        "    skonester_cw_build_tradition_picker_lists_agot_effect = yes",
        "  }",
        "  else = {",
        "    skonester_cw_build_tradition_picker_lists_vanilla_effect = yes",
        "  }",
        "}",
        "",
    ]
    out += emit_effect("skonester_cw_build_tradition_picker_lists_vanilla_effect", vanilla)
    out.append("")
    out += emit_effect("skonester_cw_build_tradition_picker_lists_agot_effect", agot)
    out.append("")

    with open(OUT, "wb") as fh:
        fh.write(b"\xef\xbb\xbf" + "\n".join(out).encode("utf-8"))
    print(f"vanilla={len(vanilla)} agot={len(agot)} -> {os.path.relpath(OUT, MOD_DIR)}")


if __name__ == "__main__":
    main()
